repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.0
  hooks:
    - id: flake8
      exclude: OMPythonFast.py
      args: ["--max-line-length=120", "--extend-ignore=E203,W503"]
- repo: local
  hooks:
    - id: pytest
      name: Run pytest
      entry: bash -c 'SKIP_DOCKER_TESTS=true PYTHONPATH=$(pwd) pytest'
      language: system
      types: [python]
