name: CI

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - dev
      - release
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests inside Docker
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace openmodelica/openmodelica:v1.24.4-ompython /bin/bash -c "
            echo 'installPackage(Modelica, \"4.0.0+maint.om\"); getErrorString();' > install.mos &&
            omc install.mos &&
            python -m pip install --upgrade pip &&
            pip install -r requirements.txt &&
            pytest
          "
